version: "3.8"

services:
  # Next.js service
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    command: >
      sh -c "pnpm install && pnpm run migrate && pnpm dev"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      AUTH_GITHUB_ID: ${AUTH_GITHUB_ID}
      AUTH_GITHUB_SECRET: ${AUTH_GITHUB_SECRET}
      AUTH_SECRET: ${AUTH_SECRET}

    depends_on:
      - postgres

  # PostgreSQL service
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432" # Map port 5432 for PostgreSQL

volumes:
  postgres_data:
