import { ThemeProvider } from "@/components/ui/ThemeProvider"
import { AuthPopover } from "@/components/ui/AuthPopover"
import localFont from "next/font/local"
import type { Metadata } from "next"
import "./globals.css"

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
})
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

const Footer = () => {
  return (
    <footer className="bg-gray-800 p-4 text-center text-white">
      <p>&copy; 2024 My App. All rights reserved.</p>
    </footer>
  )
}

const Navbar = () => {
  return (
    <div className="flex items-center justify-between p-4 dark:bg-inherit">
      <nav className="container mx-auto flex items-center justify-between">
        <p>MyApp</p>
        <AuthPopover />
      </nav>
    </div>
  )
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} grid min-h-screen grid-rows-[auto_1fr_auto] antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Navbar />
          {children}
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  )
}
